branch-defaults:
  default:
    environment: null
  master:
    environment: CoffeeShop-env-test
deploy:
  artifact: target/shop-ui-0.0.7-SNAPSHOT.jar
environment-defaults:
  CoffeeShop-env-test:
    branch: null
    repository: null
global:
  application_name: CoffeeShop
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
